app/models/business.rb, db/migrate/20160816201509_remove_columns_from_users.rb, db/migrate/20160816201916_change_table_name.rb, db/migrate/20160816202741_remove_status_from_user.rb, db/migrate/20160816203327_change_order_gnomes.rb, db/migrate/20160816203713_change_order_items.rb, db/migrate/20160816204058_add_item_ref_to_order_items.rb, db/migrate/20160816210457_create_businesses.rb, db/migrate/20160816210637_business_items.rb, db/schema.rb, schema.xml, spec/factories.rb, spec/models/business_spec.rb
updated schema 
* reference schema.xml
=> New schema

db/seeds.rb
* 20 businesses
* 50 items per business
=> [WIP]-Business seeds

db/seeds.rb
Started seed file with businesses and items
=> seed file class methods and start call

app/views/items/show.html.erb, spec/features/visitor_adds_items_to_cart_from_items_pages_spec.rb
Small change to Item view page (no styling, just functionality) to satisfy user story. 13 examples, 3 failures, 1 pending in spec overall status
=> minimal functionality on item show page, passes user story

db/seeds.rb
seeded Orders with Items and relationships successfully created. 13 examples, 1 failure, 1 pending
=> OrderItem relationships seeded successfully

app/controllers/business_admins_controller.rb, app/models/user.rb, app/models/user_role.rb, app/views/business_admins/edit.html.haml, app/views/business_admins/new.html.haml, config/routes.rb, db/seeds.rb, spec/features/business_admin_can_manage_businesses_other_admin_spec.rb
24 tests passing, 1 skipped (business model spec)
=> Business Admin specs passing

app/controllers/businesses_controller.rb, app/models/business.rb, app/views/shared/_business_admin_dashboard.html.haml, spec/features/business_admin_can_update_business_info_spec.rb, spec/features/user_can_checkout_spec.rb, spec/features/visitor_can_view_categories_page_spec.rb
these commits add a few sad paths and push our test coverage up to 84%.
=> Business admin sad paths

app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/models/category.rb, app/services/permissions_service.rb, app/views/cart/show.html.haml, app/views/users/new.html.haml, spec/factories.rb, spec/features/user_can_checkout_spec.rb, spec/features/user_can_edit_own_information_spec.rb, spec/features/user_sees_past_orders_spec.rb, spec/features/visitor_can_login_spec.rb, spec/features/visitor_can_view_categories_page_spec.rb, spec/features/visitor_must_log_in_to_checkout_spec.rb
permissions_services have been fully implemented. some tests, controllers, and views have been changed to reflect the functionality. 
factories.rb and permissions_service.rb have been heavily updated.
test coverage is now sitting at an impressive 93.42%. :)
=> Permissions services implementation

app/models/user.rb, spec/models/role_spec.rb, spec/models/user_spec.rb
Merged locally. No conflicts.
All specs passing. Added methods to User.
=> user_spec passing

app/controllers/application_controller.rb, app/views/users/show.html.haml, config/routes.rb, db/migrate/20160823202129_add_status_to_business.rb, db/schema.rb, spec/features/user_can_apply_for_new_business_spec.rb
implementation of test is still in progress, but the test is created, as well as a new migration for adding a status column to our businesses table. this will enable @concach and I to continue implementing the new business approval process.
don't forget to rake db:migrate after pulling down.
=> add migration for status column in business, test complete, failing

app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, spec/models/user_spec.rb
Minor changes. Eliminated whitespace. Added flash messages.
=> Updated session flash messages

app/models/user.rb, spec/models/user_spec.rb
All tests passing. Ready to merge. Disregard comments below.
remove_business_admin does not appear to be deleting record from the database. Not sure
why. Tried destroy, destroy_all, delete, delete_all, looked at validation. Please ensure
that the test is written properly. Currently commented out in user_spec.
=> User spec test updates ready to merge

app/controllers/business_admins_controller.rb, app/controllers/businesses_controller.rb, app/controllers/users_controller.rb, app/models/business.rb, app/models/user.rb, app/views/business_admins/edit.html.haml, app/views/business_admins/new.html.haml, app/views/shared/_business_admin_dashboard.html.haml, app/views/shared/_platform_admin_dashboard.html.haml, app/views/users/show.html.haml, db/seeds.rb, spec/features/platform_admin_shares_permissions_of_business_admin_spec.rb, spec/support/test_helper.rb
all 5 newly written specs passing
=> Platform admins share permissions #15

Gemfile, Gemfile.lock, app/controllers/sessions_controller.rb, app/views/sessions/new.html.haml, config/initializers/omniauth.rb, config/routes.rb
Coverage down to 94.4% but OAuth using Twitter works! The caveat is that username has to be identical to the twitter nickname because Twitter does not provide email addresses. I will try to build on this to allow signup with Twitter at a later point if there's time.
=> Twitter OAuth works! and RSPec passing

app/controllers/businesses_controller.rb, app/services/permissions_service.rb, app/views/shared/_platform_admin_dashboard.html.haml, config/routes.rb, db/seeds.rb, spec/features/platform_admin_can_approve_or_deny_a_new_business_spec.rb
And can toggle a business online and offline. All tests passing. Major changes in PA dashboard. Test for card 13 passing. Card 14 to be written, though functionality was dictated by card 13. No styling. Button styling not working on new buttons.
=> Platform admin can add or decline a business

app/views/businesses/show.html.erb, db/seeds.rb, spec/features/platform_admin_can_approve_or_deny_a_new_business_spec.rb, spec/features/platform_admin_can_toggle_businesses_online_status_spec.rb, spec/support/test_helper.rb
PA can toggle businesses online and offline.
=> Final platform admin test passing

app/services/permissions_service.rb, spec/features/business_admin_can_manage_businesses_other_admin_spec.rb
fixed some permissions, tweaked a few tests for coverage.
=> permissions tweaks, test coverage 95.6%

app/controllers/businesses_controller.rb, app/views/shared/_platform_admin_dashboard.html.haml, spec/features/platform_admin_can_approve_or_deny_a_new_business_spec.rb, spec/support/test_helper.rb
last bit of base functionality implemented. test coverage 95.62%
=> business id set for new business_admins on approval of new business, test passes

app/controllers/admin/items_controller.rb, app/models/item.rb, spec/features/business_admin_can_edit_own_business_items_spec.rb
add tests for admin items sad paths, refactor admin items controller, add validations for item model
=> add tests, refactor, validations

app/views/items/show.html.erb
small PR to add item description to show page.
=> add description to items show page

app/assets/javascripts/home.js, app/controllers/business_admins_controller.rb, app/models/business.rb, app/services/permissions_service.rb, app/views/business_admins/show.html.haml, app/views/shared/_platform_admin_dashboard.html.haml, config/routes.rb, spec/features/platform_admin_can_view_businesses_items_to_edit_spec.rb, spec/features/platform_admin_shares_permissions_of_business_admin_spec.rb
Functionality in place. Categories don't seem to be populating. Minor navbar modification.
=> Platform admin can view a businesses items spec passing

app/models/business.rb, app/views/shared/_platform_admin_dashboard.html.haml
=> Refactored the platform admin dashboard to remove enums etc
